# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  rime-moegirl = {
    pname = "rime-moegirl";
    version = "20250309";
    src = fetchurl {
      url = "https://github.com/outloudvi/mw2fcitx/releases/download/20250309/moegirl.dict.yaml";
      sha256 = "sha256-LUKh0UMU0WVIWAGWogzWjqEVKCY7TTvWRueMeFxVslk=";
    };
  };
  yazi-rs-plugins = {
    pname = "yazi-rs-plugins";
    version = "cb6165b25515b653a70f72a67889579d190facfe";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "cb6165b25515b653a70f72a67889579d190facfe";
      fetchSubmodules = false;
      sha256 = "sha256-XDz67eHmVM5NrnQ/uPXN/jRgmrShs80anWnHpVmbPO8=";
    };
    date = "2025-03-12";
  };
}
